# Generated by Django 4.2.13 on 2024-05-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='bookcopy_id',
            field=models.CharField(default='000', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
