# Generated by Django 4.2 on 2024-05-22 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0002_rack"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLibraryRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.library",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "library")},
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="libraries",
            field=models.ManyToManyField(
                related_name="users",
                through="user.UserLibraryRelation",
                to="library.library",
            ),
        ),
    ]
