# Generated by Django 4.2 on 2024-05-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookborrow",
            name="is_returned",
            field=models.BooleanField(default=False),
        ),
    ]
