# Generated by Django 4.2 on 2024-05-23 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book", "0002_bookborrow_is_returned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookborrow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books_borrowed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
