# Generated by Django 4.2 on 2024-05-23 17:01

from django.db import migrations, models
import django.db.models.deletion
import library_api.fields


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_alter_bookborrow_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcopy",
            name="order",
            field=library_api.fields.IncrementingField(
                blank=True, default=0, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookcopy",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_copies",
                to="book.book",
            ),
        ),
    ]
